name: Deploy to GCP VM

on:
  push:
    branches:
      - dev-gamini

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: 'projects/696839999639/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider'
        service_account: 'github-actions-sa@project-95fc7c4c-71c2-4a91-931.iam.gserviceaccount.com'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Trigger VM Redeployment via SSH
      run: |
        gcloud compute ssh ubuntu@job-notifier-vm \
        --zone "asia-south1-a" \
        --project "project-95fc7c4c-71c2-4a91-931" \
        --command "sudo systemctl restart google-startup-scripts.service" \
        --quiet
